### ISSUE TITLE
Provide pref to bail instead of downloading if file already exists

### ISSUE THREAD

**Issue by NoneGiven** [TheRealMarnes/doubleclick-image-downloader#17]
When the file already exists at the target path, the extension increments a counter until it's able to find a filename it can save with. In other words, double click an image twice and you'll get "cool_file.jpg" and "cool_file_1.jpg".

This can be useful, but in my use cases I would prefer not to download the file (and get a notification telling me the file already exist instead). So, we can introduce a preference (false by default) that will prevent downloading in this case.

I'll submit a PR for this. I worry whether this will be possible in the WebExtensions version, though...

**Comment by TheRealMarnes** [comment]
Off the top of my head, it wont be. As for the firefox version, a pull
request would be much appreciated, thanks. Ive completely lost interest in
working on the firefox versions myself.

On 24 May 2017 16:02, "NoneGiven" <notifications@github.com> wrote:

When the file already exists at the target path, the extension increments a
counter until it's able to find a filename it can save with. In other
words, double click an image twice and you'll get "cool_file.jpg" and
"cool_file_1.jpg".

This can be useful, but in my use cases I would prefer not to download the
file (and get a notification telling me the file already exist instead).
So, we can introduce a preference (false by default) that will prevent
downloading in this case.

I'll submit a PR for this. I worry whether this will be possible in the
WebExtensions version, though...

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/TheRealMarnes/doubleclick-image-downloader/issues/17>,
or mute the thread

**Comment by NoneGiven** [comment]
I see the current Chrome version uses "uniquify" to resolve a duplicate filename, but it could possibly use "prompt"? That would work fine for me, too. Firefox seems to support it as well.

I can look into it and make a PR for the WebExtensions version, if you don't mind. Same deal, add a preference to use "prompt" instead of adding a counter automatically.

**Comment by TheRealMarnes** [comment]
Sounds good
