### ISSUE TITLE
Download Button

### ISSUE THREAD

**Issue by githubadmin-KAJ** [TheRealMarnes/doubleclick-image-downloader#20]
Download button appears above image (outside the bounds of the image when the mouse cursor is hovering over the image) and when cursor leaves image to click the download button, the button disappears (as the cursor is no longer hovering over the image)

**Comment by TheRealMarnes** [comment]
Include a link to the page where your bugs happen next time to provide complete information, please - unless you mean it happens with every image on every site, which I doubt.

This happens on some sites because of their specific CSS markup and shenanigans like position: relative; and other annoying trickery... Not much I can do about it unless I get lucky and figure out a better "truth formula" for the image's actual display location.
